# Generated by Django 6.0.4 on 2026-04-13 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_communityarea_area_id_alter_communityarea_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityarea',
            name='id',
        ),
        migrations.AlterField(
            model_name='communityarea',
            name='area_id',
            field=models.IntegerField(blank=True, default=999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurantpermit',
            name='community_area_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.communityarea'),
        ),
    ]
