# Generated by Django 6.0.4 on 2026-04-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_remove_communityarea_id_alter_communityarea_area_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpermit',
            name='community_area_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.SET_DEFAULT, to='map.communityarea'),
        ),
    ]
