# Generated by Django 6.0.4 on 2026-04-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_restaurantpermit_community_area_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantpermit',
            old_name='community_area_id',
            new_name='community_area',
        ),
    ]
