# Generated by Django 6.0.4 on 2026-04-13 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_rename_community_area_id_restaurantpermit_community_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpermit',
            name='community_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.communityarea'),
        ),
    ]
