# Generated by Django 6.0.4 on 2026-04-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_restaurantpermit_community_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpermit',
            name='application_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantpermit',
            name='issue_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantpermit',
            name='community_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='map.communityarea'),
        ),
    ]
